spring:
  application:
    name: service-consumer
server:
  port: 8765  #??????????
eureka:
  instance:
    prefer-ip-address: true #???????IP??
  client:
    serviceUrl: #???????????
      defaultZone: http://127.0.0.1:8761/eureka/
